switch annotation from sensio/framework-extra-bundle to symfony/routing
claroline/Distribution pull request #6838
Opened 2020-09-17 14:02 UTC by GrimpEreau

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Fixed issues |

2020-09-17 14:08 UTC, Elorfin approved these changes

2020-09-17 14:20 UTC, chalasr requested changes
This seems to break tests. No merge please, looking at it.

2020-09-17 16:12 UTC, chalasr commented on main/core/Controller/APINew/Template/TemplateController.php
> +     *     methods={"PUT"}
This is the culprit! It's not a Route but a ParamConverter :)

2020-09-18 10:07 UTC, Elorfin commented on main/core/Controller/APINew/User/LocationController.php
> +     * @Route("/{id}/geolocate", name="apiv2_location_geolocate@", methods={"GET"})
I think this is a typo.

2020-09-18 10:10 UTC, chalasr commented on main/core/Controller/APINew/User/LocationController.php
> +     * @Route("/{id}/geolocate", name="apiv2_location_geolocate@", methods={"GET"})
Good catch, fixed. thanks

2020-09-18 12:22 UTC, chalasr approved these changes

2020-09-20 07:58 UTC, merged