WIP - Switch swiftmailer with mailer
claroline/Distribution pull request #6961
Opened 2020-11-23 15:50 UTC by Zowac

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Fixed issues | comma-separated list of issues fixed by the PR, if any

2020-11-25 12:39 UTC, chalasr requested changes
Great work so far!

2020-11-25 12:39 UTC, chalasr commented on main/core/Library/Mailing/Client/SymfonyMailer.php
> +        } catch (\Exception $e) {
Only exceptions from the symfony/mailer component need to be caught (https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Mailer/Exception/ExceptionInterface.php)

2020-11-25 12:39 UTC, chalasr commented on main/core/Library/Mailing/Client/SymfonyMailer.php
> +            );
nitpick: should be on one line :)

2020-11-25 12:39 UTC, chalasr commented on main/core/Library/Mailing/TransportFactory.php
> +use Symfony\Component\EventDispatcher\EventDispatcherInterface;
```suggestion
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;
```

2020-11-25 12:39 UTC, chalasr commented on main/core/Library/Mailing/TransportFactory.php
> +use Monolog\Logger;
Better use high-level abstractions.

```suggestion
use Psr\Log\LoggerInterface;
```

2020-11-25 12:39 UTC, chalasr commented on main/core/Library/Mailing/TransportFactory.php
> +    private const TIME_OUT = 30;
in one word: `TIMEOUT` :)

2020-11-25 12:39 UTC, chalasr commented on main/core/Library/Mailing/TransportFactory.php
> +        $encryption = null;
```suggestion
        $encryption = null; // Lets the transport choose the best value based on the platform.
```

2020-11-25 12:39 UTC, chalasr commented on main/core/Library/Mailing/TransportFactory.php
> +        if (!empty($this->configHandler->getParameter('mailer_encryption')) && 'none' !== $this->configHandler->getParameter('mailer_encryption')) {
As briefly discussed, `none` should mean "no encryption"  (i.e. `false`). The check should be updated accordingly

2020-11-25 12:39 UTC, chalasr commented on main/core/Tests/Unit/Library/Mailing/Client/MailerTest.php
> +class MailerTest extends MockeryTestCase
```suggestion
class SymfonyMailerTest extends MockeryTestCase
```

2020-11-25 12:39 UTC, chalasr commented on main/core/Tests/Unit/Library/Mailing/Client/MailerTest.php
> +    public function testEmailWithMessageData()
This test does not bring much value as it is more about testing the `Email` class which is already tested on symfony side. I suggest to remove it

2020-11-25 12:39 UTC, chalasr commented on main/core/Tests/Unit/Library/Mailing/Client/MailerTest.php
> +    public function getMessageData()
The body of this method can be directly inlined in `testSend()` above, given it is the only relevant test

2020-11-25 12:39 UTC, chalasr commented on main/core/Library/Mailing/Client/SymfonyMailer.php
> +        } catch (\Exception $e) {
Also I suggest to log that an error occurred while trying to send the mail, with the exception passed in the log context.

2020-11-25 12:39 UTC, chalasr commented on main/core/DependencyInjection/Compiler/DynamicConfigPass.php
>              new Reference('Claroline\CoreBundle\Library\Mailing\TransportFactory'),
`Swift_Transport` does not exist anymore (line 32) :) 
The class should be `TransportInterface` from symfony/mailer (because it is a factory, we can use a broader type, no need to set concrete class).

2020-11-25 12:39 UTC, chalasr commented on main/core/DependencyInjection/Compiler/DynamicConfigPass.php
> +        $container->removeDefinition('mailer.default_transport');
That `mailer.default_transport` should be configured somewhere :)
What is missing here is to replace the suggested config for `swiftmailer` by a minimal config for `mailer` (which will make the framework create the `@mailer` and `@mailer.default_transport` services).

2020-11-25 15:10 UTC, chalasr commented on main/core/DependencyInjection/Compiler/DynamicConfigPass.php
> +        $transport->setClass('TransportInterface');
`TransportInterface::class` (with import for ` Symfony\Component\Mailer\Transport\TransportInterface`)

2020-11-25 15:26 UTC, Zowac commented on main/core/DependencyInjection/Compiler/DynamicConfigPass.php
> +        $transport->setClass('TransportInterface');
Oops, fixed, thx :)

2020-11-26 09:37 UTC, chalasr commented on main/core/Library/Mailing/Client/SymfonyMailer.php
> +            $this->logger->error($e->getMessage());
```suggestion
            $this->logger->error($e->getMessage(), ['exception' => $e]);
```

2020-11-26 09:37 UTC, chalasr commented on main/core/Library/Mailing/TransportFactory.php
> +        $transport->setSourceIp(null);
Does this method actually exist?

2020-11-26 10:33 UTC, Zowac commented on main/core/Library/Mailing/Client/SymfonyMailer.php
> +            $this->logger->error($e->getMessage());
Done, thx :)

2020-11-26 10:37 UTC, Zowac commented on main/core/Library/Mailing/TransportFactory.php
> +        $transport->setSourceIp(null);
Yes, but i forget `getStream` before and after cheking the method doesn't support null value, i removed this line. Thanks you

2020-11-26 10:37 UTC, Zowac commented on main/core/DependencyInjection/Compiler/DynamicConfigPass.php
>              new Reference('Claroline\CoreBundle\Library\Mailing\TransportFactory'),
Done, thx :)

2020-11-26 10:48 UTC, Zowac commented on main/core/Library/Mailing/Client/SymfonyMailer.php
> +        } catch (\Exception $e) {
Done, thx :)

2020-11-26 10:48 UTC, Zowac commented on main/core/Library/Mailing/Client/SymfonyMailer.php
> +            );
Done, thx :)

2020-12-03 10:38 UTC, chalasr requested changes

2020-12-03 10:38 UTC, chalasr commented on main/core/Library/Mailing/Client/SymfonyMailer.php
> +        } catch (ExceptionInterface $e) {
I just realized that the `Mailer` class is responsible for catching mailing-related errors and logging them to a specific file. Let's remove the try-catch

2020-12-03 10:55 UTC, Zowac commented on main/core/Library/Mailing/Client/SymfonyMailer.php
> +        } catch (ExceptionInterface $e) {
Indeed, thank you :)

2020-12-03 13:41 UTC, chalasr approved these changes
👍  Tested locally, all good (both smtp and gmail).
Thanks @Zowac

2020-12-03 13:52 UTC, Zowac commented
Thanks for your help @chalasr

2020-12-11 08:00 UTC, Elorfin requested changes
Thank you for the work.
It just needs little changes to make `postal` work on our existing platforms.

2020-12-11 08:00 UTC, Elorfin commented on main/core/Library/Mailing/TransportFactory.php
> +            $this->configHandler->getParameter('mailer_port'),
It is `null` when using postal. It breaks the container compilation so we can't migrate it and it should be handled by code.

```
$this->configHandler->getParameter('mailer_port') ?? 0,
```

2020-12-11 08:00 UTC, Elorfin commented on main/core/Library/Mailing/TransportFactory.php
> +        $transport->setPassword($this->configHandler->getParameter('mailer_password'));
Same thing with `mailer_username` and `mailer_transport`, `null` values are not allowed by `EsmtpTransport`.

2020-12-11 09:25 UTC, Zowac commented
@Elorfin 

The changes are done, thank you for your feedback :)

2020-12-11 09:38 UTC, Elorfin approved these changes

2020-12-11 09:38 UTC, merged